name: isolated_download_manager
description: File download manager based on reusable isolates with progress, cancellation, pause and resume
repository: https://github.com/starkdmi/download_manager
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  download_task: ^1.0.1
  http: '>=0.13.0 <=0.13.5'
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
