name: isolated_download_manager
description: File download manager based on reusable isolates with progress, cancellation, pause and resume
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  http: ^0.13.4
  download_task: 
    path: /Users/starkdmi/Code/Languages/Dart/resumable_download
    # git:
    #   url: https://github.com/starkdmi/resumable_download
    #   ref: main

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
