name: isolated_download_manager
description: File download manager based on reusable isolates with progress, cancellation, pause and resume
repository: https://github.com/starkdmi/download_manager
version: 1.0.3

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  download_task: '>=1.0.2 <2.0.0'
  http: '>=0.13.0 <2.0.0'

dev_dependencies:
  lints: '>=0.1.0 <3.0.0'
  test: '>=1.16.0 <2.0.0'
